name: Push to master

on:
  push:
    branches:
      - '*'

jobs:
  deel_job:
    if: github.ref == 'refs/heads/deel'
    runs-on: ubuntu-latest
    steps:
    # the checkout action persists the passed credentials by default
    # subsequent git commands will pick them up automatically
    - uses: actions/checkout@v2
     # Add steps specific to mylo branch
